# Generated by Django 6.0 on 2025-12-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("project_type", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("image", models.ImageField(upload_to="projects/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
