# Generated by Django 6.0 on 2026-01-10 11:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("internships", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internship",
            name="cv",
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name="cv"),
        ),
        migrations.AlterField(
            model_name="internship",
            name="letter",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="letter"
            ),
        ),
    ]
